apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-config-app
  labels:
    app: custom-config-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-config-app
  template:
    metadata:
      labels:
        app: custom-config-app
    spec:
      volumes:
        - name: custom-volume
          persistentVolumeClaim:
            claimName: custom-pvc	
      containers:
      - image: registry.redhat.io/rhel8/httpd-24
        name: httpd
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 8443
          name: https-port
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: custom-volume
            mountPath: /custom_config
